name: Test and Deploy to Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: introduction

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: introduction/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # A telepítés átkerült ide, a Python beállítása utánra!
      - name: Install MkDocs
        run: pip install mkdocs-material

      - name: Test (Typecheck)
        run: pnpm tsc

      - name: Build React App
        run: pnpm build

      # Most már hiba nélkül le fog futni az építés
      - name: Build Documentation
        run: mkdocs build -f mkdocs.yml --site-dir dist/docs

      - name: Create 404 page for SPA
        run: cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: introduction/dist

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
